
services:

  traefik:
    image: "traefik:latest"
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${ROOT_DIR}/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
