name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - shell: bash
        env:
          ROOT_DIR: ${{ secrets.ROOT_DIR }}
          QBITTORRENT_HOST_URL: ${{ secrets.QBITTORRENT_HOST_URL }}
          SOULSEEK_HOST_URL: ${{ secrets.SOULSEEK_HOST_URL }}
          SOULSEEK_BASIC_AUTH_CREDENTIALS: ${{ secrets.SOULSEEK_BASIC_AUTH_CREDENTIALS }}
          DEEMIX_HOST_URL: ${{ secrets.DEEMIX_HOST_URL }}
          PLEX_CLAIM: ${{ secrets.PLEX_CLAIM }}
          NEXTCLOUD_HOST_URL: ${{ secrets.NEXTCLOUD_HOST_URL }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          ACME_EMAIL: ${{ secrets.ACME_EMAIL }}
          TRAEFIK_HOST_URL: ${{ secrets.TRAEFIK_HOST_URL }}
          TRAEFIK_BASIC_AUTH_CREDENTIALS: ${{ secrets.TRAEFIK_BASIC_AUTH_CREDENTIALS }}
        run: |
          cat << EOF > docker-compose/.env
          # common
          ROOT_DIR=$ROOT_DIR

          # media-sharing.yaml
          QBITTORRENT_HOST_URL=$QBITTORRENT_HOST_URL
          SOULSEEK_HOST_URL=$SOULSEEK_HOST_URL
          SOULSEEK_BASIC_AUTH_CREDENTIALS=$SOULSEEK_BASIC_AUTH_CREDENTIALS
          DEEMIX_HOST_URL=$DEEMIX_HOST_URL

          # media-streaming.yaml
          PLEX_CLAIM=$PLEX_CLAIM

          # nextcloud.yaml
          NEXTCLOUD_HOST_URL=$NEXTCLOUD_HOST_URL
          MYSQL_USER=$MYSQL_USER
          MYSQL_PASSWORD=$MYSQL_PASSWORD

          # traefik.yaml
          ACME_EMAIL=$ACME_EMAIL
          TRAEFIK_HOST_URL=$TRAEFIK_HOST_URL
          TRAEFIK_BASIC_AUTH_CREDENTIALS=$TRAEFIK_BASIC_AUTH_CREDENTIALS
          EOF
     
      - shell: bash
        run: cat docker-compose/.env